train:
  batch_size: 64
  epochs: 150
  learning_rate: 0.0002
  shuffle: true
  model_filename: "simple_imitation_model.pt"
  shift_signs: [-2.0, -1.0, 0.0, 1.0, 2.0]
  vel_offset: 0.2
  save_intermediate_models: true
  tensorboard_logging: true
  use_pretrained_resnet: true    # ImageNet事前学習済みモデルを使用
  freeze_resnet_backbone: false # ResNetバックボーンを凍結するか